change ordering, include distributions in search, include totalcount
comic/grand-challenge.org pull request #1661
Opened 2020-12-18 12:57 UTC by Kicksta

2020-12-18 13:07 UTC, Kicksta commented
Since moving to WSL2, I am using VS code and I haven't got black and flake8 configured. Will try to get that back in place and recommit.

2020-12-18 13:21 UTC, jmsmkn requested changes
I've made a few suggestions that should reduce the number of database calls for this as every time you call `queryset.count()` the query is executed. Please check if it works as intended when they're all applied.

What I've changed it to - we store the count of the unfiltered queryset on the view object in L30, then filter it in the rest of `get_queryset`, then lookup the number again in L126.

2020-12-18 13:21 UTC, jmsmkn commented on app/grandchallenge/products/views.py
> +        product_total_all = queryset.count()
```suggestion
        self.product_total_all = queryset.count()
```

2020-12-18 13:21 UTC, jmsmkn commented on app/grandchallenge/products/views.py
> +                "product_total_all": Product.objects.filter(ce_status=Status.CERTIFIED).count(),
```suggestion
                "product_total_all": self.product_total_all,
```

2020-12-18 13:21 UTC, jmsmkn commented on app/grandchallenge/products/views.py
> +        print(context)
```suggestion
```

2020-12-18 13:21 UTC, jmsmkn commented on app/grandchallenge/products/views.py
> +    product_total_all = queryset.count()
```suggestion
```

2021-01-07 14:31 UTC, jmsmkn commented
Did this work? I was making the suggestions blind. Also, did you get pre-commit set back up?

2021-01-07 19:48 UTC, Kicksta commented
The code worked, checked it before the holidays, but I am having trouble with pre-commit. If I understand correctly [it isn't available for Ubuntu 20.04](https://packages.ubuntu.com/search?keywords=pre-commit&searchon=names&suite=focal&section=all). So after some googling figured out I could use [snap](https://snapcraft.io/install/pre-commit/ubuntu) for it. But using `snap install pre-commit` gives the following: `error: cannot communicate with server: Post http://localhost/v2/snaps/pre-commit: dial unix /run/snapd.socket: connect: no such file or directory` Now I have found two options of which both I am not sure what they do and I am somewhat hesitant to give them a try, however it seems to help people with similar issues: [option 1](https://github.com/microsoft/WSL/issues/2374#issuecomment-699110721), [option 2](https://github.com/DamionGans/ubuntu-wsl2-systemd-script). Any advice on which one to try while not breaking things...?

2021-01-07 20:25 UTC, jmsmkn commented
The best way is via pip, they provide a single command to set everything up

```
curl https://pre-commit.com/install-local.py | python -
```

See https://pre-commit.com/#installation

2021-01-11 13:56 UTC, jmsmkn approved these changes

2021-01-11 13:56 UTC, merged