Markdown editor with preview and editor tabs
comic/grand-challenge.org pull request #1953
Opened 2021-08-09 16:05 UTC by HarmvZ

https://user-images.githubusercontent.com/2001094/128737744-7466182a-a223-42da-a281-0b5f5dc9f468.mp4

2021-08-09 16:11 UTC, jmsmkn requested changes
I don't think that this will work with multiple widgets in the same form. Can you update all ids, hrefs, and arias to include `{{ widget.attrs.id }}`?

2021-08-09 16:24 UTC, jmsmkn commented
Also can you check how this is in the admin?

2021-08-10 07:44 UTC, HarmvZ commented
> I don't think that this will work with multiple widgets in the same form. Can you update all ids, hrefs, and arias to include {{ widget.attrs.id }}?

Good catch, that did not work indeed. Fixed it now.

The admin also did not work as it should because it was missing the vendor bootstrap js files. Added those also. The spacing/indentation is a bit strange, but I think that's not really important. It looks like this:

![image](https://user-images.githubusercontent.com/2001094/128827802-6a2134b8-9e9b-4fc0-b58e-c1244e09add4.png)

2021-08-10 08:36 UTC, jmsmkn approved these changes

2021-08-10 08:36 UTC, merged