Add view archive item button
comic/grand-challenge.org pull request #2328
Opened 2022-03-21 13:59 UTC by amickan

Adds a "View archive item" button to the archive item list view. This should only be merged once the Cirrus side changes are live. 
![2022-03-21 14_43_38-Gc](https://user-images.githubusercontent.com/30069334/159276759-0d484116-d3ec-4d35-8bf5-148b7b90daa2.png)

2022-03-21 14:55 UTC, HarmvZ requested changes

2022-03-21 14:55 UTC, HarmvZ commented on app/config/settings.py
> +WORKSTATIONS_ARCHIVE_ITEM_QUERY_PARAM = "archive-item"
Change to camelCase to be in line with other parameters.

```suggestion
WORKSTATIONS_ARCHIVE_ITEM_QUERY_PARAM = "archiveItem"
```

2022-03-22 10:01 UTC, HarmvZ approved these changes

2022-03-22 10:14 UTC, jmsmkn commented
I think it's OK to merge this before the CIRRUS changes are deployed, CIRRUS will show an error to the users for the time being but this saves having a PR hanging around for a while.

2022-03-22 10:15 UTC, merged