Fix for showing limited number of github repos
comic/grand-challenge.org pull request #2627
Opened 2022-08-04 12:08 UTC by miriam-groeneveld

Fix issue where only the first 30 github app installations and repos were retrieved.
Default parameter per_page is increased from 30 (default) to 100(max).
Request is repeated until all items are retrieved.

Closes #2299

2022-08-05 07:50 UTC, jmsmkn requested changes
Unfortunately a recursive get is not possible in a request-response cycle, makes it really easy for a user to DOS the site by keeping all of the workers occupied making requests to GitHub. We can only really do one  or two calls to an external API per request as even one call occupies a worker for up to 5 seconds - an age when our response time target is 100ms. To fully solve this we will need to add some filtering with the calls hooked in to an auto complete endpoint.

Increasing `per_page` to 100 is a good idea and maybe make a separate PR with just that change?

2022-08-05 08:18 UTC, miriam-groeneveld commented
> Unfortunately a recursive get is not possible in a request-response cycle, makes it really easy for a user to DOS the site by keeping all of the workers occupied making requests to GitHub. We can only really do one or two calls to an external API per request as even one call occupies a worker for up to 5 seconds - an age when our response time target is 100ms. To fully solve this we will need to add some filtering with the calls hooked in to an auto complete endpoint.
> 
> Increasing `per_page` to 100 is a good idea and maybe make a separate PR with just that change?

Ah, that's not something I considered. What about caching the result? The github endpoint does not seem to have a way to filter or search, so only increasing the default will not solve the issue. DIAGNijmegen has more than 500 repos already.

2022-08-05 08:24 UTC, jmsmkn commented
Then rather than using autocomplete we would need to implement pagination and select.

2022-08-09 05:40 UTC, miriam-groeneveld commented
Simple increase of default for now; addressed in #2634

2022-08-09 05:40 UTC, closed without merging