Adds annotation type component interface to development fixtures
comic/grand-challenge.org pull request #2717
Opened 2022-12-13 08:21 UTC by miriam-groeneveld

Needed to be able to test https://github.com/DIAGNijmegen/rse-gcapi/pull/144

2022-12-13 09:14 UTC, chrisvanrun commented
This doesn't work because the `strict=True` is a python 3.10 feature.

2022-12-13 09:16 UTC, chrisvanrun commented on scripts/development_fixtures.py
> +    annotation_interface.save()
This should likely be cherry-picked on top of:
- https://github.com/comic/grand-challenge.org/pull/2715

2022-12-13 09:17 UTC, chrisvanrun requested changes
Doesn't work for python 3.8 (default python Django runs underatm)

2022-12-14 10:03 UTC, jmsmkn approved these changes
LGTM, there is a tight coupling from the gcapi tests to some of the things in this file, probably they should be separated out and added to a new separate set of fixtures managed in gcapi itself.

2022-12-14 10:03 UTC, merged