Fix buggy code blocks in markdown renderer
comic/grand-challenge.org pull request #3764
Opened 2024-12-20 15:52 UTC by chrisvanrun

Closes #3592

## Old HTML render:

<img width="837" alt="image" src="https://github.com/user-attachments/assets/35e3c016-e95d-43d0-bdc2-93a427294073" />

## New HTML render:

<img width="837" alt="image" src="https://github.com/user-attachments/assets/090f807d-3abe-4bc6-a74d-e30e9f3d46a3" />

Likely this PR fixes some other incorrect visuals since the base extension only handled snippets. I've only discovered the `<code>` one.

2024-12-20 15:54 UTC, chrisvanrun commented on app/tests/core_tests/test_markdown.py
> -    "markdown_with_html, expected_output",
There were needlessly complex.

2025-01-07 14:21 UTC, koopmant commented
I propose to add some extra css to fix a missing bottom margin after the codeblocks have been converted:
in `app/grandchallenge/core/static/css/base.scss`:
```
div.codehilite {
    margin-bottom: $paragraph-margin-bottom;
}
```

![image](https://github.com/user-attachments/assets/d114d8f6-3152-4041-b439-dff6b1b1c052)
⤹
![image](https://github.com/user-attachments/assets/f20d5e8e-c764-40d5-b806-87e0f9a9ed5a)

2025-01-07 14:21 UTC, jmsmkn commented on app/grandchallenge/core/templatetags/bleach.py
> +        post_processors = [YOUTUBE_TAG_SUBSTITUTION, *post_processors]
Why does `YOUTUBE_TAG_SUBSTITUTION` need to be first now?

2025-01-07 14:23 UTC, jmsmkn commented on app/grandchallenge/core/utils/markdown.py
> +        # Make extensions safe
Escaping is not the same as safety.

2025-01-07 14:24 UTC, jmsmkn commented on app/grandchallenge/core/utils/markdown.py
> +        self.clean_tag_classes = {
These are not clean classes, they're escaped classes.

2025-01-07 14:25 UTC, jmsmkn commented on app/grandchallenge/core/utils/markdown.py
> +        # Make extensions safe
Why do they anyway need to be stripped and escaped if they are provided by the class configuration?

2025-01-07 14:28 UTC, jmsmkn commented on app/grandchallenge/core/utils/markdown.py
> +        input_is_safe = isinstance(html, SafeString)
In what situations in the codebase does this extension work with safe html?

2025-01-07 14:28 UTC, chrisvanrun commented on app/grandchallenge/core/templatetags/bleach.py
> +        post_processors = [YOUTUBE_TAG_SUBSTITUTION, *post_processors]
The post_processors, such as applying GC-specific classes, should happen way at the end as final clean-up. The `YOUTUBE_TAG_SUBSTITUTION`, if IIRC, doesn't introduce any targed HTML-tags. Still I thought it better to have the system-wide post_processors have the final say in the html.

2025-01-07 14:29 UTC, jmsmkn commented on app/grandchallenge/core/utils/markdown.py
> +            new_markup = mark_safe(new_markup)
I do not think that we can be certain that the modifications done are safe.

2025-01-08 07:34 UTC, jmsmkn commented on app/grandchallenge/core/utils/markdown.py
> +    """
Why is preserving them necessary?

2025-01-08 07:35 UTC, jmsmkn commented on app/config/settings.py
> +        }
This class is only used once and the configuration is static, it would be better if this configuration is just done on the class once so that the logic is not split up in multiple places unnecessarily.

2025-01-08 07:38 UTC, jmsmkn commented on app/grandchallenge/core/templatetags/bleach.py
> +        post_processors = [YOUTUBE_TAG_SUBSTITUTION, *post_processors]
They have different properties - the `YOUTUBE_TAG_SUBSTITUTION` is adding things which are not allowed by cleaning the html. `ExtendHTMLTagClasses` is only adding things which are allowed. `ExtendHTMLTagClasses` should be done before `clean` on L85, and the `mark_safe` handling should be removed from `ExtendHTMLTagClasses`.

2025-01-08 07:40 UTC, jmsmkn requested changes
This needs to be reworked so that `mark_safe` is not used as this opens up XSS vulnerabilities.

2025-01-08 09:27 UTC, jmsmkn commented on app/grandchallenge/core/templatetags/bleach.py
> +        post_processors = [YOUTUBE_TAG_SUBSTITUTION, *post_processors]
I'm still wondering why this cannot be done using the standard markdown processors. Shouldn't it be implemented as a https://python-markdown.github.io/reference/markdown/postprocessors/ ? e.g.:

```python
from markdown.extensions import Extension
from markdown.postprocessors import Postprocessor
from bs4 import BeautifulSoup

class ClassMapPostprocessor(Postprocessor):
    def run(self, html):
        soup = BeautifulSoup(html, 'html.parser')

        class_map = {
            "img": ["img-fluid"],
            "blockquote": ["blockquote"],
            "table": ["table", "table-hover", "table-borderless"],
            "thead": ["thead-light"],
            "code": ["codehilite"]
        }
        
        for element in soup.find_all([*class_map.keys()]):
            existing_classes = element.get('class', [])
            element['class'] = existing_classes + self.class_map[element.name]

        return str(soup)

class ClassMapExtension(Extension):
    def extendMarkdown(self, md):
        post_processor = ClassMapPostprocessor(md)
        md.postprocessors.register(post_processor, 'class_map', 100)
```

2025-01-08 10:29 UTC, jmsmkn commented on app/grandchallenge/core/templatetags/bleach.py
> +        post_processors = [YOUTUBE_TAG_SUBSTITUTION, *post_processors]
I spent too long trying to understand this that I ended up implementing it, as Chris is off today I will push and go with it as I think this is the way to go. We lose the email obfuscation as discussed but that can be replaced by a tag if absolutely necessary. I don't think that in 2025 it is.

2025-01-08 11:55 UTC, jmsmkn approved these changes

2025-01-08 12:59 UTC, merged